# Generated by Django 4.0.2 on 2022-02-12 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evening',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EveningWhisky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CleanTastings.evening')),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose', models.IntegerField()),
                ('taste', models.IntegerField()),
                ('evening_whisky', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CleanTastings.eveningwhisky')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eveningwhisky',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CleanTastings.whisky'),
        ),
        migrations.AddField(
            model_name='evening',
            name='whiskies',
            field=models.ManyToManyField(through='CleanTastings.EveningWhisky', to='CleanTastings.Whisky'),
        ),
    ]
