# Generated by Django 4.0.2 on 2022-02-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CleanTastings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eveningwhisky',
            options={'verbose_name_plural': 'EveningWhiskies'},
        ),
        migrations.AlterModelOptions(
            name='whisky',
            options={'verbose_name_plural': 'Whiskies'},
        ),
    ]
