# Generated by Django 4.0.2 on 2022-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanTastings', '0002_alter_eveningwhisky_options_alter_whisky_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='nose',
            field=models.IntegerField(verbose_name='nose/Geruch (0-10)'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='taste',
            field=models.IntegerField(verbose_name='taste/Geschmack (0-10)'),
        ),
    ]
