# Generated by Django 4.0.2 on 2022-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanTastings', '0003_alter_tasting_nose_alter_tasting_taste'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eveningwhisky',
            constraint=models.UniqueConstraint(fields=('evening', 'whisky'), name='evening_whisky'),
        ),
    ]
