# Generated by Django 4.0.2 on 2022-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanTastings', '0004_eveningwhisky_evening_whisky'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.UniqueConstraint(fields=('evening_whisky', 'user'), name='evening_whisky_user'),
        ),
    ]
