# Generated by Django 4.0.2 on 2022-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanTastings', '0005_tasting_evening_whisky_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(check=models.Q(('nose__gte', 0)), name='nose_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(check=models.Q(('nose__lte', 10)), name='nose_lte_10'),
        ),
    ]
