# Generated by Django 4.0.2 on 2022-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanTastings', '0006_tasting_nose_gte_0_tasting_nose_lte_10'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasting',
            name='nose_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='tasting',
            name='nose_lte_10',
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(check=models.Q(('nose__gte', 0), ('nose__lte', 10)), name='nose_between_0_10'),
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(check=models.Q(('taste__gte', 0), ('taste__lte', 10)), name='taste_between_0_10'),
        ),
    ]
