# Generated by Django 4.0.2 on 2022-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanTastings', '0007_remove_tasting_nose_gte_0_remove_tasting_nose_lte_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='nose',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nose/Geruch (0-10)'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='taste',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='taste/Geschmack (0-10)'),
        ),
    ]
