# Generated by Django 4.0.2 on 2022-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicalGroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='comment',
            field=models.CharField(default='doof', max_length=128),
            preserve_default=False,
        ),
    ]
