# Generated by Django 4.0.2 on 2022-02-11 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models3.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models3.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('owner_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models3.owneraccount')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='accounts',
            field=models.ManyToManyField(through='models3.OwnerAccount', to='models3.Account'),
        ),
    ]
