# Generated by Django 4.0.2 on 2022-02-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('whisky', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DateWhisky',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('whisky', models.ManyToManyField(to='models2.Whisky')),
            ],
        ),
        migrations.CreateModel(
            name='DateUserWhisky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose', models.IntegerField()),
                ('taste', models.IntegerField()),
                ('dateuser', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models2.dateuser')),
                ('whisky', models.ManyToManyField(to='models2.Whisky')),
            ],
        ),
        migrations.AddField(
            model_name='dateuser',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models2.datewhisky'),
        ),
        migrations.AddField(
            model_name='dateuser',
            name='user',
            field=models.ManyToManyField(to='models2.User'),
        ),
    ]
