# Generated by Django 4.0.2 on 2022-02-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evening',
            fields=[
                ('evening', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('whisky', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Whiskies',
            },
        ),
        migrations.CreateModel(
            name='EveningTasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose', models.IntegerField()),
                ('taste', models.IntegerField()),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models2.evening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evening',
            name='whisky',
            field=models.ManyToManyField(to='models2.Whisky'),
        ),
    ]
