# Generated by Django 4.0.2 on 2022-02-11 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiskyTasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose', models.IntegerField()),
                ('taste', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='evening',
            old_name='whisky',
            new_name='whiskies',
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='whisky',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='EveningTasting',
        ),
        migrations.AddField(
            model_name='whiskytasting',
            name='evening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models2.evening'),
        ),
        migrations.AddField(
            model_name='whiskytasting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whiskytasting',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models2.whisky'),
        ),
    ]
