# Generated by Django 4.0.2 on 2022-02-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models2', '0002_whiskytasting_rename_whisky_evening_whiskies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whisky',
            old_name='name',
            new_name='whisky',
        ),
    ]
